//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolManagementSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class Department
    {
        public Department()
        {
            this.Courses = new HashSet<Course>();
        }
    
        public int DepartmentID { get; set; }
        public string Name { get; set; }
        public Nullable<double> Budget { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<int> Administrator { get; set; }
    
        public virtual ICollection<Course> Courses { get; set; }
    }
}
